name: 'notion-jam'
author: victornpb
description: 'A export Notion pages to markdown and images to be used as JAM stack (static website, github pages, eleventy...)'
branding:
  color: gray-dark
  icon: book
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  NOTION_SECRET:
    description: 'Notion API Token secret'
    required: true
  NOTION_DATABASE:
    description: 'Notion Database URL or ID (example: https://notion.so/00112233445566778899aabbccddeeff)'
    required: true
  ARTICLE_PATH:
    description: 'Path template to where to save markdown files (default="posts/{title}/index.md")'
    required: false
  ASSETS_PATH:
    description: 'Path to save images, if started with . will be relative to ARTICLE_PATH, otherwise absolute (default=".")'
    required: false
  PARALLEL_PAGES:
    description: '(default=3)'
    required: false
  PARALLEL_DOWNLOADS_PER_PAGE:
    description: '(default=3)'
    required: false
  DOWNLOAD_IMAGE_TIMEOUT:
    description: '(default=30)'
    required: false
  SKIP_DOWNLOADED_IMAGES:
    description: '(default=true)'
    required: false

runs:
  
  using: node16
  main: dist/action.mjs
